version: "3.9"

services:
  postgres:
    image: postgres:17

    container_name: agricom-postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: agricom_docker_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .

    container_name: agricom-backend

    depends_on:
      - postgres

    ports:
      - "5000:5000"

    env_file:
      - .env

volumes:
  postgres_data:
